<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-LEKBI2B9" failures="3" tests="4" name="Test" time="19.628" errors="0" timestamp="2025-04-06T22:31:24 IST">
  <testcase classname="TestCases.TC003_LoginDataDrivenTest" name="verify_LoginDDT" time="5.27"/>
  <testcase classname="TestCases.TC003_LoginDataDrivenTest" name="verify_LoginDDT" time="2.522">
    <failure type="java.lang.AssertionError" message="Login succeeded despite invalid credentials.">
      <![CDATA[java.lang.AssertionError: Login succeeded despite invalid credentials.
at TestCases.TC003_LoginDataDrivenTest.verify_LoginDDT(TC003_LoginDataDrivenTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="TestCases.TC003_LoginDataDrivenTest" name="verify_LoginDDT" time="2.488">
    <failure type="java.lang.AssertionError" message="Login succeeded despite invalid credentials.">
      <![CDATA[java.lang.AssertionError: Login succeeded despite invalid credentials.
at TestCases.TC003_LoginDataDrivenTest.verify_LoginDDT(TC003_LoginDataDrivenTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="TestCases.TC003_LoginDataDrivenTest" name="verify_LoginDDT" time="2.501">
    <failure type="java.lang.AssertionError" message="Login succeeded despite invalid credentials.">
      <![CDATA[java.lang.AssertionError: Login succeeded despite invalid credentials.
at TestCases.TC003_LoginDataDrivenTest.verify_LoginDDT(TC003_LoginDataDrivenTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- Test -->
